apiVersion: v1
kind: Pod
metadata:
  name: mvc-webapi
spec:
  containers:
    - name: mvc
      image: mvc:latest
      ports:
        - containerPort: 5000   

    - name: webapi
      image: webapi:latest
      ports:
        - containerPort: 5000
