apiVersion: v1
kind: Pod
metadata:
  name: mvc_webapi_pod
spec:
  containers:
    - name: mvc
      image: mvc
      ports:
        - containerPort: 5000   

    - name: webapi
      image: webapi
      ports:
        - containerPort: 5000
