apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mvcappdeployment
  labels:
    app: my-mvcapp
spec:
  replicas: 4
  strategy:
    type: RollingUpdate # This is the default
    rollingUpdate:
      maxSurge: 1  #Default 25%
      maxUnavailable: 1  # Default 25%
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-mvcapp
    spec:
      containers:
      - name: my-mvcappcontainer
        image: karthik1409docker/mvcwebapps:v1
        ports:
        - containerPort: 5000    