apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
   name: mysecretprovider
   namespace: mynamespace
spec:
  provider: aws
  parameters:
    objects: -|
      - objectName: "mysecret"
        objectType: "secretsmanager"
          jmesPath:
            - path: secret1
              objectAlias: s1
            - path: secret2
              objectAlias: s2