kind: Pod
apiVersion: v1
metadata:
  name: nginx-secrets-store-inline
  namespace: mynamespace
spec:
  serviceAccountName: myserviceaccount
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - name: mysecretvolume
      mountPath: "/mysecrets"
  volumes:
    - name: mysecretvolume
      csi:
        driver: secrets-store.csi.k8s.io
        volumeAttributes:
          secretProviderClass: "mysecretprovider"