kind: Pod
apiVersion: v1
metadata:
  name: secrets-store-inline
  namespace: mynamespace
spec:
  serviceAccountName: myserviceaccount
  containers:
  - image: karthik1409docker/angularapps:v1
    name: mycontainer
    volumeMounts:
    - name: mysecretvolume
      mountPath: "/mysecrets"
      readOnly: true  #read only
  volumes:
    - name: mysecretvolume
      csi:
        #driver: secrets-store.csi.k8s.io
        driver: secrets-store.csi.k8s.io
        readOnly: true
        volumeAttributes:
          secretProviderClass: "mysecretprovider"