apiVersion: v1
kind: Pod
metadata:
  name: webapi-usesecret-pod
  labels:
    app: webapi-usesecret
spec:
  volumes:
    - name: myvolume
      secret:
      name: mysecret
  containers:
    - name: webapi-usesecret-container
      image: karthik1409docker/configmapsecretsapps:webapisecretapp
      ports:
        - containerPort: 7000
      volumeMounts:
        - name: myvolume
          mountPath: /mysecrets
---
apiVersion: v1
kind: Service
metadata:
  name: secretappsvc
spec:
  selector: 
    app: webapi-usesecret
  type: NodePort
  ports:
    - name: http
      port: 3000
      targetPort: 7000  
      nodePort: 30000
