apiVersion: v1 
kind: ConfigMap 
metadata:
  name: example-configmap 
data:
  #Configuration values can be set as key-value properties
  MESSAGE: Hello from example-configmap
---
apiVersion: v1
kind: Pod
metadata:
  name: webapi-useconfigmap-pod
  labels:
    app: webapi-useconfigmap
spec:
  volumes:
    - name: myvolume
      configMap:
        name: example-configmap
  containers:
    - name: webapi-useconfigmap-container
      image: karthik1409docker/configmapsecretsapps:webapi
      ports:
        - containerPort: 7000
      volumeMounts:
        - name: myvolume
          mountPath: /config
