apiVersion: v1
kind: Pod
metadata:
  name: webapi-usesecret-pod
  labels:
    app: webapi-usesecret
spec:
  containers:
    - name: webapi-usesecret-container
      image: karthik1409docker/configmapsecretsapps:webapisecretapp
      ports:
        - containerPort: 7000
      envFrom:
        - secretRef:
            name: mysecret
